using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace StockExchangeYahooFinance.Helpers
{
    public class YModulesFields
    {
        public string EndDate = "endDate";
        public string Fmt = "fmt";
        public string TotalRevenue = "totalRevenue";
        public string CostOfRevenue = "costOfRevenue";
        public string GrossProfit = "grossProfit";
        public string ResearchDevelopment = "researchDevelopment";
        public string SellingGeneralAdministrative = "sellingGeneralAdministrative";
        public string NonRecurring = "nonRecurring";
        public string OtherOperatingExpenses = "otherOperatingExpenses";
        public string TotalOperatingExpenses = "totalOperatingExpenses";
        public string OperatingIncome = "operatingIncome ";
        public string TotalOtherIncomeExpenseNet = "totalOtherIncomeExpenseNet";
        public string Ebit = "ebit";
        public string InterestExpense = "interestExpense";
        public string IncomeBeforeTax = "incomeBeforeTax";
        public string IncomeTaxExpense = "incomeTaxExpense";
        public string MinorityInterest = "minorityInterest";
        public string DiscontinuedOperations = "discontinuedOperations";
        public string ExtraordinaryItems = "extraordinaryItems";
        public string EffectOfAccountingCharges = "effectOfAccountingCharges";
        public string OtherItems = "otherItems";
        public string NetIncome = "netIncome";
        public string NetIncomeApplicableToCommonShares = "netIncomeApplicableToCommonShares";
        public string NetIncomeFromContinuingOps = "netIncomeFromContinuingOps";
        public string Depreciation = "depreciation";
        public string ChangeToNetincome = "changeToNetincome";
        public string ChangeToAccountReceivables = "changeToAccountReceivables";
        public string ChangeToLiabilities = "changeToLiabilities";
        public string ChangeToOperatingActivities = "changeToOperatingActivities";
        public string TotalCashFromOperatingActivities = "totalCashFromOperatingActivities";
        public string Investments = "investments";
        public string OtherCashflowsFromInvestingActivities = "otherCashflowsFromInvestingActivities";
        public string TotalCashflowsFromInvestingActivities = "totalCashflowsFromInvestingActivities";
        public string DividendsPaid = "dividendsPaid";
        public string SalePurchaseOfStock = "salePurchaseOfStock";
        public string NetBorrowings = "netBorrowings";
        public string TotalCashFromFinancingActivities = "totalCashFromFinancingActivities";
        public string EffectOfExchangeRate = "effectOfExchangeRate";
        public string ChangeInCash = "changeInCash";
        public string OtherCashflowsFromFinancingActivities = "otherCashflowsFromFinancingActivities";
        public string ChangeToInventory = "changeToInventory";
        public string CapitalExpenditures = "capitalExpenditures";
        public string InsidersPercentHeld = "insidersPercentHeld";
        public string InstitutionsPercentHeld = "institutionsPercentHeld";
        public string InstitutionsFloatPercentHeld = "institutionsFloatPercentHeld";
        public string InstitutionsCount = "institutionsCount";
        public string PeRatio = "peRatio";
        public string PegRatio = "pegRatio";
        public string Estimates = "estimates";
        public string Period = "period";
        public string Growth = "growth";
        public string StrongBuy = "strongBuy";
        public string Buy = "buy";
        public string Hold = "hold";
        public string Sell = "sell";
        public string StrongSell = "strongSell";
        public string EpochGradeDate = "epochGradeDate";
        public string Firm = "firm";
        public string ToGrade = "toGrade";
        public string FromGrade = "fromGrade";
        public string Action = "action";
        public string ReportDate = "reportDate";
        public string Organization = "organization";
        public string PctHeld = "pctHeld";
        public string Position = "position";
        public string Value = "value";
        // financialData Modul
        public string CurrentPrice = "currentPrice";
        public string TargetHighPrice = "targetHighPrice";
        public string TargetLowPrice = "targetLowPrice";
        public string TargetMeanPrice = "targetMeanPrice";
        public string TargetMedianPrice = "targetMedianPrice";
        public string RecommendationMean = "recommendationMean";
        public string RecommendationKey = "recommendationKey";
        public string NumberOfAnalystOpinions = "numberOfAnalystOpinions";
        public string TotalCash = "totalCash";
        public string TotalCashPerShare = "totalCashPerShare";
        public string Ebitda = "ebitda";
        public string TotalDebt = "totalDebt";
        public string QuickRatio = "quickRatio";
        public string CurrentRatio = "currentRatio";
        public string DebtToEquity = "debtToEquity";
        public string RevenuePerShare = "revenuePerShare";
        public string ReturnOnAssets = "returnOnAssets";
        public string ReturnOnEquity = "returnOnEquity";
        public string GrossProfits = "grossProfits";
        public string FreeCashflow = "freeCashflow";
        public string OperatingCashflow = "operatingCashflow";
        public string EarningsGrowth = "earningsGrowth";
        public string RevenueGrowth = "revenueGrowth";
        public string GrossMargins = "grossMargins";
        public string EbitdaMargins = "ebitdaMargins";
        public string OperatingMargins = "operatingMargins";
        public string ProfitMargins = "profitMargins";
    }
}
